/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SafetyScoreRouteImport } from './routes/safety-score'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyScoreRoute = SafetyScoreRouteImport.update({
  id: '/safety-score',
  path: '/safety-score',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/safety-score': typeof SafetyScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/safety-score': typeof SafetyScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/safety-score': typeof SafetyScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/live-monitoring'
    | '/login'
    | '/register'
    | '/safety-score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/live-monitoring'
    | '/login'
    | '/register'
    | '/safety-score'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/live-monitoring'
    | '/login'
    | '/register'
    | '/safety-score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SafetyScoreRoute: typeof SafetyScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-score': {
      id: '/safety-score'
      path: '/safety-score'
      fullPath: '/safety-score'
      preLoaderRoute: typeof SafetyScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SafetyScoreRoute: SafetyScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
